
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 24 23:53:15 CEST 2021
//----------------------------------------------------

package asint.cup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int Dist = 44;
  public static final int Or = 46;
  public static final int Asig = 38;
  public static final int True = 6;
  public static final int Coma = 55;
  public static final int Sum = 33;
  public static final int Ig = 41;
  public static final int Null = 8;
  public static final int If = 10;
  public static final int LCie = 53;
  public static final int Of = 32;
  public static final int Delete = 21;
  public static final int Real = 28;
  public static final int Var = 25;
  public static final int Record = 19;
  public static final int Menor = 39;
  public static final int Else = 12;
  public static final int Variable = 4;
  public static final int Sep = 59;
  public static final int Read = 22;
  public static final int Mayor = 40;
  public static final int Pointer = 30;
  public static final int Then = 11;
  public static final int Res = 34;
  public static final int PAp = 48;
  public static final int Endif = 13;
  public static final int PunCo = 58;
  public static final int Punto = 54;
  public static final int Proc = 9;
  public static final int CCie = 51;
  public static final int While = 14;
  public static final int Int = 27;
  public static final int EOF = 0;
  public static final int Not = 47;
  public static final int And = 45;
  public static final int error = 1;
  public static final int False = 7;
  public static final int Flecha = 57;
  public static final int Div = 36;
  public static final int Do = 15;
  public static final int LitCad = 5;
  public static final int MenIg = 43;
  public static final int NL = 24;
  public static final int EntNum = 2;
  public static final int PCie = 49;
  public static final int New = 20;
  public static final int String = 29;
  public static final int Mul = 35;
  public static final int RealNum = 3;
  public static final int LAp = 52;
  public static final int Mod = 37;
  public static final int MayIg = 42;
  public static final int CAp = 50;
  public static final int Type = 18;
  public static final int Bool = 26;
  public static final int Array = 31;
  public static final int Call = 17;
  public static final int Andvers = 56;
  public static final int Write = 23;
  public static final int Endwhile = 16;
}

