/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyCCConstants.java */
package asint.cc;

public interface AnalizadorSintacticoTinyCCConstants {

  int EOF = 0;
  int If = 1;
  int Else = 2;
  int Of = 3;
  int NL = 4;
  int Do = 5;
  int Or = 6;
  int And = 7;
  int Var = 8;
  int Int = 9;
  int Not = 10;
  int New = 11;
  int Proc = 12;
  int Read = 13;
  int Type = 14;
  int True = 15;
  int Real = 16;
  int Bool = 17;
  int Call = 18;
  int Null = 19;
  int Then = 20;
  int While = 21;
  int Write = 22;
  int False = 23;
  int Endif = 24;
  int Array = 25;
  int Record = 26;
  int Delete = 27;
  int String = 28;
  int Pointer = 29;
  int Endwhile = 30;
  int letra = 31;
  int digitoPositivo = 32;
  int digito = 33;
  int parteEntera = 34;
  int parteDecimal = 35;
  int parteExponencial = 36;
  int EntNum = 37;
  int RealNum = 38;
  int Variable = 39;
  int LitCad = 40;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"of\"",
    "\"nl\"",
    "\"do\"",
    "\"or\"",
    "\"and\"",
    "\"var\"",
    "\"int\"",
    "\"not\"",
    "\"new\"",
    "\"proc\"",
    "\"read\"",
    "\"type\"",
    "\"true\"",
    "\"real\"",
    "\"bool\"",
    "\"call\"",
    "\"null\"",
    "\"then\"",
    "\"while\"",
    "\"write\"",
    "\"false\"",
    "\"endif\"",
    "\"array\"",
    "\"record\"",
    "\"delete\"",
    "\"string\"",
    "\"pointer\"",
    "\"endwhile\"",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<EntNum>",
    "<RealNum>",
    "<Variable>",
    "<LitCad>",
    "<token of kind 41>",
    "<token of kind 42>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"&\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
